### PR TITLE
nxp_driver: Update the MIMXRT files to v2.10

### PR DESCRIPTION
**Pull request by robert-hh**
This PR includes the v2.10 files of the SDK for selected MIMXRT MCUs and the patch for fsl_lpi2c.c, which is part of the mcu_sdk, but not in the MCU bundles that will be provided by NXP.
This PR include support for the MIMXRT1176 MCU as well.

### CODE REVIEW

**Comment by robert-hh** [comment]
@hathach Hi. Do you need more information about the PR, or any wishes?

**Comment by robert-hh** [comment]
Closing it, since v2.11 was published.

**Comment by hathach** [comment]
@robert-hh sorry I am a bit busy with other works. Let me know if you plan to make an PR for 2.11. I guess it will be more straightforward to merge that.

**Comment by robert-hh** [comment]
Good day, @hathach. I'm testing v2.11 at the moment. It has some breaking changes. Some of them clearly unneeded, like just renaming signals or skipping names. And as before the files set provided by the SDK builder has files differing from the ones in the NXP mcux repository at https://github.com/NXPmicro/mcux-sdk. Sometimes the mcux is more recent, sometimes the SDK device packages.

**Pull request closed without merging**
